apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: nginx-lab
data:
  nginx.conf: |
    user nginx;
    worker_processes  3;
    error_log  /var/log/nginx/error.log;
    events {
      worker_connections  10240;
    }
    http {
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';

     access_log        /var/log/nginx/access.log main;

     server {
       listen       80;
       server_name  _;

       location / {
         root   /usr/share/nginx/html;
         index  index.html index.htm;
       }
    }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-lab
  labels:
    app: nginx
spec:
  replicas: 2
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: nginx  
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
              name: nginx-http
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-conf
              readOnly: true
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf     

---
apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  namespace: nginx-lab
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: LoadBalancer
